# Site settings
title: Sérgio Custódio Fertonani de Souza
description: 'Business Card Page'
url: 'https://scfertonani.github.io'
baseurl: ''
profilepic: '/images/profile.jpg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Sergio Custódio Fertonani de Souza'
  email: scfertonani@gmail.com
#  twitter_username: thomzuehlke
#  facebook_username: joshgerdes
#  github_username:  tzuehlke
  linkedin_username:  scfertonani
#  meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
